
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 09 07:59:09 CST 2013
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int BTHAN = 19;
  public static final int KW_INT = 2;
  public static final int INT = 7;
  public static final int FOR = 32;
  public static final int MINUS = 25;
  public static final int BETHAN = 21;
  public static final int IS = 37;
  public static final int NOT = 16;
  public static final int AND = 15;
  public static final int LTHAN = 20;
  public static final int OR = 14;
  public static final int P2 = 24;
  public static final int P1 = 23;
  public static final int KW_QUEUE = 5;
  public static final int DIV = 28;
  public static final int PLUS = 26;
  public static final int IF = 34;
  public static final int LETHAN = 22;
  public static final int ID = 10;
  public static final int WAIT = 31;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int EQUAL = 11;
  public static final int error = 1;
  public static final int COMA = 12;
  public static final int KW_BOOLEAN = 4;
  public static final int DEQUAL = 17;
  public static final int PCOMA = 13;
  public static final int ELSE = 35;
  public static final int PUNTO = 38;
  public static final int TO = 33;
  public static final int WHILE = 30;
  public static final int NEQUAL = 18;
  public static final int KW_STRING = 3;
  public static final int MULTI = 27;
  public static final int STRING = 8;
  public static final int LL2 = 40;
  public static final int KW_LIST = 6;
  public static final int LL1 = 39;
  public static final int NERROR = 29;
  public static final int SEND = 36;
}

